dist: trusty
sudo: required

language: node_js
node_js:
  - "8"

addons:
  sonarcloud:
    organization: "alocquet-github"
script:
  - npm run coverage
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
    - node_modules